

SET TRANSACTION READ WRITE;
ALTER SESSION SET CONSTRAINTS = DEFERRED;


INSERT INTO CCR_REF_CODES ("RCOD_ID", "RC_DOMAIN", "RC_VALUE", "RC_DESCRIPTION", "CLASSIFICATION_ID", "ACTIVE", "MODIFIED_DATE", "MODIFIED_USER", "CREATE_DATE", "CREATE_USER")
VALUES (1, 'TEST_DOMAIN', '1', 'First entry against domain [TEST_DOMAIN]', 1, 'Y', TO_TIMESTAMP('2023-08-08 12:53:50','YYYY-MM-DD HH24:MI:SS'), 'ADM_CLINICAL', TO_TIMESTAMP('2023-08-08 12:53:50','YYYY-MM-DD HH24:MI:SS'), 'ADM_CLINICAL');
ALTER SESSION SET CONSTRAINTS = IMMEDIATE;
COMMIT;